// Code generated by "traceable -type=Stringer -output=traced/stringer.go"; DO NOT EDIT.

package traced

import (
	"github.com/ConorNevin/traceable/example"
)

// TracedStringer is a traced implementation of Stringer
type TracedStringer struct {
	x example.Stringer
}
