// Code generated by "traceable -type Searcher -output searcher_traced.go"; DO NOT EDIT.

package example

import (
	"context"
	"github.com/opentracing/opentracing-go"
	"io"
)

// TracedSearcher is a traced implementation of Searcher
type TracedSearcher struct {
	x Searcher
}

func (t *TracedSearcher) Search(a0 context.Context, a1 string) error {
	span, a0 := opentracing.StartSpanFromContext(a0, "Searcher.Search")
	defer func() {
		span.Finish()
	}()
	return t.x.Search(a0, a1)
}
