// Code generated by "traceable -type=io.Writer -output=traced_writer.go"; DO NOT EDIT.

package example

import (
	"io"
)

// TracedWriter is a traced implementation of io.Writer
type TracedWriter struct {
	x io.Writer
}

func (t *TracedWriter) Write(p []byte) (n int, err error) {
	return t.x.Write(p)
}
