// Code generated by "traceable -types FooBar -output traced/foobar.go"; DO NOT EDIT.

package traced

import (
	"context"

	"github.com/ConorNevin/traceable/internal/tests/subpackage"
	"github.com/opentracing/opentracing-go"
)

// TracedFooBar is a traced implementation of FooBar
type TracedFooBar struct {
	x subpackage.FooBar
}

func (t *TracedFooBar) Foo(a0 context.Context) error {
	span, a0 := opentracing.StartSpanFromContext(a0, "FooBar.Foo")
	defer func() {
		span.Finish()
	}()
	return t.x.Foo(a0)
}
