// Code generated by "traceable -type Geometry -output geometry_traced.go"; DO NOT EDIT.

package geometry

import (
	"context"

	"github.com/opentracing/opentracing-go"
)

// TracedGeometry is a traced implementation of Geometry
type TracedGeometry struct {
	x Geometry
}

func (t *TracedGeometry) Area(a0 context.Context) (float64, error) {
	span, a0 := opentracing.StartSpanFromContext(a0, "Geometry.Area")
	defer func() {
		span.Finish()
	}()
	return t.x.Area(a0)
}
